
export const STORY_HEADINGS = [
  "The Magical Treehouse Adventure",
  "The Mystery of the Missing Toy",
  "A Dragon Who Was Afraid of Flying",
  "The Day the Animals Talked",
  "A Robot's First Day at School",
  "The Lost Astronaut in a Candy Galaxy",
  "Three Brave Knights and a Silly Giant",
  "The Pirate Who Couldn't Swim",
  "A Secret Agent Squirrel on a Mission",
  "The Princess Who Saved the Prince",
  "My Pet Dinosaur's Birthday Party",
  "The Sleepwalking Scarecrow",
  "The Magical Spaceship Powered by Laughter",
  "The Little Bear Who Couldn't Sleep",
  "The Mystery of the Missing Rainbow Color",
  "The Magical Baking Contest in Candy Land",
  "The Grumpy Cloud That Learned to Rain Fun",
  "The Knight Who Befriended a Dragon",
  "The Secret of the Whispering Woods",
  "The Time-Traveling Turtle",
  "The Penguin Who Wanted to Fly",
  "The Detective Dog and the Case of the Stolen Bone",
  "The Friendly Ghost Who Was Scared of the Dark",
  "The Mermaid Who Lost Her Voice",
  "The Boy Who Could Talk to Animals",
  "The Enchanted Crayon That Drew Real Things",
  "The Gummy Bear Who Became a King",
  "The Silly Monkey Who Opened a Banana Stand",
  "The Girl Who Planted a Jellybean Garden",
  "The Adventure of the Floating Island",
  "The Shy Star That Learned to Twinkle",
  "The Musical Forest Where Trees Sing",
  "The Robot Who Learned to Dream",
  "The Magical Clock That Could Stop Time",
  "The Secret Underwater City of Fish",
  "The Bear Who Became a Famous Chef",
  "The Quest for the Golden Acorn",
  "The Cow Who Jumped Over the Moon... For Real!",
  "The Boy Who Built a Rocket to Mars",
  "The Three Little Pigs and the Friendly Wolf",
  "The Princess Who Wore Pajamas to the Ball",
  "The Magical Toy Soldier Who Came to Life",
  "The Adventure of the Runaway Roller Coaster",
  "The Brave Little Firefly Guiding the Way",
  "The Secret Life of Garden Gnomes",
  "The Day It Rained Popcorn",
  "The Friendship Between a Cat and a Mouse",
  "The Lost Puppy's Journey Home",
  "The Dinosaur Who Went to the Dentist",
  "The Magical Sneakers That Could Run Super Fast",
  "The Mystery of the Haunted Treehouse",
  "The Superhero Who Was Powered by Kindness",
  "The Girl Who Discovered a Secret Door",
  "The Alien Who Crash-Landed in a Backyard",
  "The Talking Car's First Road Trip",
  "The Magical Library Where Books Talk",
  "The Little Cloud's Big Journey",
  "The Boy Who Could Breathe Underwater",
  "The Mystery of the Invisible Cookie Thief",
  "The Circus Elephant Who Learned to Dance",
  "The Magical Flute That Made Everyone Happy",
  "The Grumpy Troll Who Found a Friend",
  "The Day the Toys Had a Parade",
  "The Knight Who Was Afraid of Spiders",
  "The Little Boat's Big Ocean Adventure",
  "The Girl Who Could Jump on Clouds",
  "The Secret of the Hidden Waterfall",
  "The Fox Who Became a School Teacher",
  "The Magical Paintbrush That Changed Colors",
  "The Time the Sun and Moon Swapped Places",
  "The Koala Who Didn't Want to Nap",
  "The Mystery of the Echoing Cave",
  "The Rabbit Who Became the Fastest in the World",
  "The Pirate Ship That Could Fly",
  "The Girl Who Had a Pet Cloud",
  "The Magical Snow Globe with a Real Village Inside",
  "The Brave Little Ant Who Moved a Mountain",
  "The Boy Who Found a Magic Carpet",
  "The Mystery of the Missing Moon Cheese",
  "The Squirrel Who Forgot Where He Hid His Nuts",
  "The Day the Farm Animals Formed a Band",
  "The Friendly Vampire Who Loved Orange Juice",
  "The Magical Carousel That Traveled the World",
  "The Girl Who Befriended Her Shadow",
  "The Mystery of the Singing Flowers",
  "The Turtle Who Won a Race Against a Cheetah",
  "The Boy Who Climbed a Giant Beanstalk",
  "The Magical Kite That Flew to Space",
  "The Penguin Who Opened an Ice Cream Shop",
  "The Secret Agent Goldfish",
  "The Day All the Colors Faded Away",
  "The Friendly Monster Under the Bed",
  "The Magical Snowman Who Never Melted",
  "The Girl Who Sailed a Paper Boat Across the Sea",
  "The Magical Remote Control That Paused the World",
  "A Tiny Mouse with a Lion's Heart",
  "The Day the Crayons Quit and Went on Vacation"
];